"""Compatibility API for plan models, policy checks, and plan construction.

Implementation lives in `plan_models`, `plan_rules`, and `plan_builder`; callers may keep
importing the established names from `app.pipeline.plan`.
"""

from app.pipeline.validate import ValidationName

from .plan_builder import create_plan
from .plan_models import (
    _VALIDATION_ORDER,
    EmployeeId,
    FileId,
    ItemId,
    ModelName,
    Operation,
    PageIndex,
    PlanDocument,
    PlanEmployee,
    PlanIntegrityError,
    PlanItem,
    PlanSource,
    PlanValidation,
    Route,
    TargetName,
    UploadId,
    read_plan,
)
from .plan_planner import (
    _BLANK_PAGES_REASON,
    _NO_EMPLOYEE,
    _UNANALYZED_PAGES_REASON,
    _employee_guess,
    _failed,
    _file_item,
    _foreign,
    _Ownerless,
    _page_subjects,
    _Planner,
    _queued_item,
    _reads_no_person,
    _Subject,
    _unowned_item,
    _Verdict,
    _verdict_of,
)
from .plan_rules import (
    CONVERSION_OPERATIONS,
    DIRECT_OPERATIONS,
    ConversionNotAllowed,
    DirectFileTypeMismatch,
    DirectOperationForbidden,
    NoApplicableOperation,
    OperationSource,
    PhotoRulesNotMet,
    SelectedOperation,
    _operation_source_text,
    _pages_text,
    _photo_rule_text,
    _table_operation,
    _target_format,
    check_conversion,
    check_direct_file_types,
    check_direct_operation,
    check_photo_rules,
    operation_source,
    select_operation,
)

__all__ = [
    "CONVERSION_OPERATIONS",
    "ConversionNotAllowed",
    "DIRECT_OPERATIONS",
    "DirectFileTypeMismatch",
    "DirectOperationForbidden",
    "EmployeeId",
    "FileId",
    "ItemId",
    "ModelName",
    "NoApplicableOperation",
    "Operation",
    "OperationSource",
    "PageIndex",
    "PhotoRulesNotMet",
    "PlanDocument",
    "PlanEmployee",
    "PlanIntegrityError",
    "PlanItem",
    "PlanSource",
    "PlanValidation",
    "Route",
    "SelectedOperation",
    "TargetName",
    "UploadId",
    "_BLANK_PAGES_REASON",
    "_NO_EMPLOYEE",
    "_Ownerless",
    "_Planner",
    "_Subject",
    "_UNANALYZED_PAGES_REASON",
    "_VALIDATION_ORDER",
    "_Verdict",
    "_employee_guess",
    "_failed",
    "_file_item",
    "_foreign",
    "_operation_source_text",
    "_page_subjects",
    "_pages_text",
    "_photo_rule_text",
    "_queued_item",
    "_reads_no_person",
    "_table_operation",
    "_target_format",
    "_unowned_item",
    "_verdict_of",
    "check_conversion",
    "check_direct_file_types",
    "check_direct_operation",
    "check_photo_rules",
    "create_plan",
    "operation_source",
    "read_plan",
    "select_operation",
    "ValidationName",
]
