"""Belge türü kataloğu: şema ve tutarlılık kuralı (00.6.1), başlangıç tohumu (00.6.2),
YAML ↔ veritabanı eşitleme (00.6.3), panelden yönetim ve form doğrulaması (11.1), analiz
talimatına giren kompakt katalog metni ve token bütçesi (11.4), aday tür listesi, onayı ve reddi
(11.5), profil fotoğrafı kural seti (11.6).

Örneklerden tür açıklaması üretimi (11.3) burada dışa aktarılmaz, `app.catalog.describe`'dan alınır:
yapay zekâ katmanını (`app.ai`) içe aktarır, `app.ai` da bu paketi — paket başlatılırken döngü
olmasın."""

from app.catalog.candidates import (
    DETAIL_SAMPLE_LIMIT,
    LIST_SAMPLE_LIMIT,
    CandidateDecidedError,
    CandidateNotFoundError,
    CandidateSample,
    CandidateSummary,
    approve_candidate_type,
    approved_type_slug,
    count_pending_candidate_types,
    list_candidate_types,
    load_candidate_type,
    reject_candidate_type,
    sample_page_refs,
    summarize_candidates,
)
from app.catalog.form import TypeForm, TypeFormError, build_entry
from app.catalog.manage import (
    PhotoRulesUnsupportedError,
    TypeExistsError,
    TypeNotFoundError,
    TypeSummary,
    create_type,
    list_types,
    load_record,
    record_problems,
    set_photo_rules,
    set_type_active,
    update_type,
)
from app.catalog.photo_rules import (
    PHOTO_RULE_SPECS,
    PHOTO_RULE_TYPES,
    PhotoRulesError,
    PhotoRuleSetting,
    PhotoRulesForm,
    PhotoRuleSpec,
    build_photo_rules,
    enabled_photo_rules,
    read_photo_rules,
)
from app.catalog.prompt_builder import (
    CATALOG_TOKEN_BUDGET,
    CompiledCatalog,
    analyzable_types,
    compile_catalog,
    estimate_tokens,
)
from app.catalog.schema import (
    Catalog,
    CatalogEntry,
    CatalogError,
    Conversion,
    FileType,
    FrontBackLayout,
    OutputFormat,
    PageRange,
    Sides,
    layout_pages,
    validate_catalog,
)
from app.catalog.sync import CatalogImportResult, export_catalog, import_catalog
from app.catalog.yaml_io import (
    dump_catalog_yaml,
    install_seed_catalog,
    load_seed_catalog,
    parse_catalog_yaml,
    read_catalog_file,
    write_catalog_file,
)

__all__ = [
    "CATALOG_TOKEN_BUDGET",
    "DETAIL_SAMPLE_LIMIT",
    "LIST_SAMPLE_LIMIT",
    "PHOTO_RULE_SPECS",
    "PHOTO_RULE_TYPES",
    "CandidateDecidedError",
    "CandidateNotFoundError",
    "CandidateSample",
    "CandidateSummary",
    "Catalog",
    "CatalogEntry",
    "CatalogError",
    "CatalogImportResult",
    "CompiledCatalog",
    "Conversion",
    "FileType",
    "FrontBackLayout",
    "OutputFormat",
    "PageRange",
    "PhotoRuleSetting",
    "PhotoRuleSpec",
    "PhotoRulesError",
    "PhotoRulesForm",
    "PhotoRulesUnsupportedError",
    "Sides",
    "TypeExistsError",
    "TypeForm",
    "TypeFormError",
    "TypeNotFoundError",
    "TypeSummary",
    "analyzable_types",
    "approve_candidate_type",
    "approved_type_slug",
    "build_entry",
    "build_photo_rules",
    "compile_catalog",
    "count_pending_candidate_types",
    "create_type",
    "dump_catalog_yaml",
    "enabled_photo_rules",
    "estimate_tokens",
    "export_catalog",
    "import_catalog",
    "install_seed_catalog",
    "layout_pages",
    "list_candidate_types",
    "list_types",
    "load_candidate_type",
    "load_record",
    "load_seed_catalog",
    "parse_catalog_yaml",
    "read_catalog_file",
    "read_photo_rules",
    "record_problems",
    "reject_candidate_type",
    "sample_page_refs",
    "set_photo_rules",
    "set_type_active",
    "summarize_candidates",
    "update_type",
    "validate_catalog",
    "write_catalog_file",
]
