"""Yapay zekâ analiz katmanı: sayfa analizi sözleşmesi (03.1), sağlayıcı soyutlaması (03.2),
analiz talimatı (03.4), tür açıklaması sözleşmesi (11.3.1), fotoğraf kontrolü sözleşmesi (11.7.1) ve
Telegram belge isteği sözleşmesi (12.3.1)."""

from app.ai.document_query import (
    DocumentQuery,
    DocumentQueryError,
    QueryIntent,
    validate_document_query,
)
from app.ai.photo_check import (
    PhotoCheck,
    PhotoCheckError,
    PhotoRuleResult,
    PhotoRuleVerdict,
    validate_photo_check,
)
from app.ai.prompts import PageAnalysisInstructions, build_page_analysis_instructions
from app.ai.provider import (
    PROVIDER_FACTORIES,
    AnalysisProvider,
    DocumentQueryRequest,
    PageAnalysisRequest,
    PageImage,
    PhotoCheckRequest,
    ProviderConfigError,
    ProviderConnectionError,
    ProviderError,
    ProviderRateLimitError,
    ProviderServerError,
    TypeDescriptionRequest,
    create_provider,
)
from app.ai.schemas import (
    EMPLOYEE_FIELDS,
    ISO_639_1_CODES,
    FieldReading,
    PageAnalysis,
    PageAnalysisError,
    PageContact,
    PagePerson,
    Script,
    Side,
    validate_page_analysis,
)
from app.ai.type_description import (
    FieldLocation,
    MrzDescription,
    TypeDescription,
    TypeDescriptionError,
    validate_type_description,
)

__all__ = [
    "EMPLOYEE_FIELDS",
    "ISO_639_1_CODES",
    "PROVIDER_FACTORIES",
    "AnalysisProvider",
    "DocumentQuery",
    "DocumentQueryError",
    "DocumentQueryRequest",
    "FieldLocation",
    "FieldReading",
    "MrzDescription",
    "PageAnalysis",
    "PageAnalysisError",
    "PageAnalysisInstructions",
    "PageAnalysisRequest",
    "PageContact",
    "PageImage",
    "PagePerson",
    "PhotoCheck",
    "PhotoCheckError",
    "PhotoCheckRequest",
    "PhotoRuleResult",
    "PhotoRuleVerdict",
    "ProviderConfigError",
    "ProviderConnectionError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderServerError",
    "QueryIntent",
    "Script",
    "Side",
    "TypeDescription",
    "TypeDescriptionError",
    "TypeDescriptionRequest",
    "build_page_analysis_instructions",
    "create_provider",
    "validate_document_query",
    "validate_page_analysis",
    "validate_photo_check",
    "validate_type_description",
]
