"""Yapay zekâ analiz katmanı: sayfa analizi sözleşmesi (03.1), sağlayıcı soyutlaması (03.2),
analiz talimatı (03.4), tür açıklaması sözleşmesi (11.3.1), tür taslağı sözleşmesi (11.5.5),
eğitim sınıflandırması sözleşmesi (11.9.3), fotoğraf kontrolü sözleşmesi (11.7.1) ve Telegram belge
isteği sözleşmesi (12.3.1)."""

from app.ai.document_query import (
    DocumentQuery,
    DocumentQueryError,
    QueryIntent,
    validate_document_query,
)
from app.ai.photo_check import (
    PhotoCheck,
    PhotoCheckError,
    PhotoRuleResult,
    PhotoRuleVerdict,
    validate_photo_check,
)
from app.ai.profile_answer import ProfileAnswer, ProfileAnswerError, validate_profile_answer
from app.ai.prompts import PageAnalysisInstructions, build_page_analysis_instructions
from app.ai.provider import (
    PROVIDER_FACTORIES,
    AnalysisProvider,
    DocumentQueryRequest,
    PageAnalysisRequest,
    PageImage,
    PhotoCheckRequest,
    ProfileAnswerRequest,
    ProviderConfigError,
    ProviderConnectionError,
    ProviderError,
    ProviderRateLimitError,
    ProviderServerError,
    TrainingClassificationRequest,
    TypeDescriptionRequest,
    TypeProposalRequest,
    create_provider,
)
from app.ai.schemas import (
    EMPLOYEE_FIELDS,
    ISO_639_1_CODES,
    FieldReading,
    PageAnalysis,
    PageAnalysisError,
    PageContact,
    PagePerson,
    Script,
    Side,
    validate_page_analysis,
)
from app.ai.training_classification import (
    TrainingClassification,
    TrainingClassificationError,
    validate_training_classification,
)
from app.ai.type_description import (
    FieldLocation,
    MrzDescription,
    TypeDescription,
    TypeDescriptionError,
    validate_type_description,
)
from app.ai.type_proposal import TypeProposal, TypeProposalError, validate_type_proposal

__all__ = [
    "EMPLOYEE_FIELDS",
    "ISO_639_1_CODES",
    "PROVIDER_FACTORIES",
    "AnalysisProvider",
    "DocumentQuery",
    "DocumentQueryError",
    "DocumentQueryRequest",
    "ProfileAnswer",
    "ProfileAnswerError",
    "ProfileAnswerRequest",
    "validate_profile_answer",
    "FieldLocation",
    "FieldReading",
    "MrzDescription",
    "PageAnalysis",
    "PageAnalysisError",
    "PageAnalysisInstructions",
    "PageAnalysisRequest",
    "PageContact",
    "PageImage",
    "PagePerson",
    "PhotoCheck",
    "PhotoCheckError",
    "PhotoCheckRequest",
    "PhotoRuleResult",
    "PhotoRuleVerdict",
    "ProviderConfigError",
    "ProviderConnectionError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderServerError",
    "QueryIntent",
    "Script",
    "Side",
    "TrainingClassification",
    "TrainingClassificationError",
    "TrainingClassificationRequest",
    "TypeDescription",
    "TypeDescriptionError",
    "TypeDescriptionRequest",
    "TypeProposal",
    "TypeProposalError",
    "TypeProposalRequest",
    "build_page_analysis_instructions",
    "create_provider",
    "validate_document_query",
    "validate_page_analysis",
    "validate_photo_check",
    "validate_training_classification",
    "validate_type_description",
    "validate_type_proposal",
]
