"""Yapay zekâ analiz katmanı: sayfa analizi sözleşmesi (03.1), sağlayıcı soyutlaması (03.2),
analiz talimatı (03.4) ve tür açıklaması sözleşmesi (11.3.1)."""

from app.ai.prompts import PageAnalysisInstructions, build_page_analysis_instructions
from app.ai.provider import (
    PROVIDER_FACTORIES,
    AnalysisProvider,
    PageAnalysisRequest,
    PageImage,
    ProviderConfigError,
    ProviderConnectionError,
    ProviderError,
    ProviderRateLimitError,
    ProviderServerError,
    TypeDescriptionRequest,
    create_provider,
)
from app.ai.schemas import (
    EMPLOYEE_FIELDS,
    ISO_639_1_CODES,
    FieldReading,
    PageAnalysis,
    PageAnalysisError,
    PageContact,
    PagePerson,
    Script,
    Side,
    validate_page_analysis,
)
from app.ai.type_description import (
    FieldLocation,
    MrzDescription,
    TypeDescription,
    TypeDescriptionError,
    validate_type_description,
)

__all__ = [
    "EMPLOYEE_FIELDS",
    "ISO_639_1_CODES",
    "PROVIDER_FACTORIES",
    "AnalysisProvider",
    "FieldLocation",
    "FieldReading",
    "MrzDescription",
    "PageAnalysis",
    "PageAnalysisError",
    "PageAnalysisInstructions",
    "PageAnalysisRequest",
    "PageContact",
    "PageImage",
    "PagePerson",
    "ProviderConfigError",
    "ProviderConnectionError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderServerError",
    "Script",
    "Side",
    "TypeDescription",
    "TypeDescriptionError",
    "TypeDescriptionRequest",
    "build_page_analysis_instructions",
    "create_provider",
    "validate_page_analysis",
    "validate_type_description",
]
