"""Eğitim modu (PRD 11.9, PLAN.md §C86): yalnız bilinen belgelerin örneklerini besler — çalışan,
kişi eşleştirmesi, kuyruk öğesi, yükleme partisi ya da çıktı belgesi oluşturmaz.

Bilinen türler (katalog + hazır önerilen türler) `known_types`, çalıştırma, staging ve örneğe
yerleştirme `placement`, yapay zekâsız tür tanıma (SHA-256, ipucunun yapı kuralları, PDF metin
katmanında MRZ) `mechanical` modülündedir. Mekanik tanınmayan öğenin yapay zekâ incelemesi ve "AI
kararı" etiketiyle yerleşmesi (11.9.3) `app.training.classification`'dadır; işçinin boş-zaman
çerçevesine bağlı olduğu için paketten dışa aktarılmaz (içe aktarma döngüsü olmasın).
"""

from app.training.known_types import (
    CATALOG_KINDS,
    KnownType,
    KnownTypes,
    KnownTypeSource,
    SuggestedTypeRow,
    SuggestedTypesError,
    build_known_types,
    load_known_types,
    load_suggested_types,
    normalize_type_name,
    parse_suggested_types,
)
from app.training.mechanical import (
    MRZ_DOC_KINDS,
    MRZ_STATE_CODES,
    ExampleInventory,
    MechanicalOutcome,
    MrzEvidence,
    MrzReading,
    MrzSearchStatus,
    Recognition,
    RecognitionBasis,
    find_mrz_readings,
    hint_label,
    load_example_inventory,
    mrz_doc_kind,
    parse_example_inventory,
    read_mrz_evidence,
    recognize,
    recognize_item,
    stage_and_recognize,
)
from app.training.placement import (
    LABEL_BY_METHOD,
    PENDING_STATUSES,
    PLACEABLE_STATUSES,
    SYSTEM_ACTOR,
    ItemNotPlaceableError,
    Placement,
    UnknownTypeError,
    create_run,
    leave_unplaced,
    place_example,
    refresh_run,
    stage_file,
)

__all__ = [
    "CATALOG_KINDS",
    "LABEL_BY_METHOD",
    "MRZ_DOC_KINDS",
    "MRZ_STATE_CODES",
    "PENDING_STATUSES",
    "PLACEABLE_STATUSES",
    "SYSTEM_ACTOR",
    "ExampleInventory",
    "ItemNotPlaceableError",
    "KnownType",
    "KnownTypeSource",
    "KnownTypes",
    "MechanicalOutcome",
    "MrzEvidence",
    "MrzReading",
    "MrzSearchStatus",
    "Placement",
    "Recognition",
    "RecognitionBasis",
    "SuggestedTypeRow",
    "SuggestedTypesError",
    "UnknownTypeError",
    "build_known_types",
    "create_run",
    "find_mrz_readings",
    "hint_label",
    "leave_unplaced",
    "load_example_inventory",
    "load_known_types",
    "load_suggested_types",
    "mrz_doc_kind",
    "normalize_type_name",
    "parse_example_inventory",
    "parse_suggested_types",
    "place_example",
    "read_mrz_evidence",
    "recognize",
    "recognize_item",
    "refresh_run",
    "stage_and_recognize",
    "stage_file",
]
